### PR TITLE
Fix failed load model test

### LINKED ISSUE #58: Failed load model test

### PR DESCRIPTION
**Pull request by jswark**

### CODE REVIEW

**Review by ikryukov — CHANGES_REQUESTED** [review]
need cleanup + add destruct window

File: tests/modelloader/test_model.cpp [hunk 1]
```diff
@@ -4,60 +4,19 @@
...
-
-    bool init = mUi->init(init_info, r->getSwapChainImageFormat(), r->getWindow(), r->getFramesData()[0].cmdPool, r->getFramesData()[0].cmdBuffer, r->getSwapChainExtent().width, r->getSwapChainExtent().height);
-    bool fonts = mUi->uploadFonts(init_info, r->getFramesData()[0].cmdPool, r->getFramesData()[0].cmdBuffer);
-}
-
-TEST_CASE("load model")
-{
-    Render r = initVK();
-    nevk::TextureManager* mTexManager = r.getTexManager();
+    nevk::TextureManager* mTexManager = new nevk::TextureManager(r.getDevice(), r.getPhysicalDevice(), r.getResManager());
```
Comment (jswark) [inline tests/modelloader/test_model.cpp:19]: \+ clear allocated memory for texmanager x3

**Review by ikryukov — APPROVED** [review]
